
data_path: E:\Dataset\Pheno4D\h5_maize_2048_align.h5

device: cuda:0
#model: dgcnn
# pointnet2
# fusion_net
model: model.fusion_net
num_class: 3

s_point: 2048

# fusion net
spatial_shape: 20
point_dims: [9, 32]
voxel_dims: [32, 64, 128, 256, 512]
weight: [5, 0.6, 4.4]

optimizer: Adma
learning_rate: 0.0001
epoch: 100
batch_size: 2

log_dir: ./logs